<script setup lang="ts">
import BackGammon from './components/BackGammon.vue';
</script>

<template>
  <div class="container">
    <h2>
      Game generated by AI with
      <a href="https://pixijs.com/" target="_blank">pixi.js</a>
    </h2>
    <BackGammon />
  </div>
</template>

<style scoped>
.container {
  margin: auto;
  text-align: center;
}
</style>
